// Thứ tự ảnh hưởng đến sidebar item selected
export const pathConstants = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  // ================= page =================
  CREATE_QUOTE: "/create-quote",
  // DETAIL_QUOTE: "/quote/:id",
  DETAIL_QUOTE: (id = ":id") => `/quote/${id}`,
  EDIT_QUOTE: (id = ":id") => `/edit-quote/${id}`,
  EMPLOYEE_MANAGEMENT: "/employee-management",
  WORK_SHIFT: "/employee-management/work-shift",
  EMPLOYEE: "/employee-management/employee",
  ROLE: "/employee-management/role",
  PERMISSION: "/employee-management/permission",
  SERVICE_MANAGEMENT: "/service-management",
  SERVICE: "/service-management/service",
  SERVICE_GROUP: "/service-group",
  SUPPLEMENT: "/service-management/supplement",
  PAYMENT_METHOD: "/payment-method",
  VOUCHER: "/voucher",
  VOUCHER_STATISTIC: (code = ":code") => `/voucher-statistic/${code}`,
  VOUCHER_HISTORY: `/voucher/history`,
  VOUCHER_LIST: `/voucher/list`,
  COMPLETED_QUOTES: "/completed-quotes",
  PENDING_QUOTES: "/pending-quotes",
  // ========checkpage=========
  CHECK: "/check",
  CHECK_BY_EMPLOYEE: "/check/by-employee",
  CHECK_BY_EMPLOYEE_DISCOUNT: "/check/by-employee-discount",
  CHECK_BY_PAYMENT_METHOD: "/check/by-payment-method",
  CHECK_BY_TIP: "/check/by-tip",
  // ========statistic page=========
  STATISTIC: "/statistic",
  STATISTIC_BY_SERVICE: "/statistic/by-service",
  STATISTIC_BY_EMPLOYEE: "/statistic/by-employee",
  STATISTIC_BY_EMPLOYEE_DISCOUNT: "/statistic/by-employee-discount",
  STATISTIC_BY_PAYMENT_METHOD: "/statistic/by-payment-method",
  STATISTIC_BY_TIP: "/statistic/by-tip",
  // statistic summary
  STATISTIC_SUMMARY: "/statistic-summary",
  STATISTIC_SUMMARY_BY_SERVICE: "/statistic-summary/by-service",
  STATISTIC_SUMMARY_BY_EMPLOYEE: "/statistic-summary/by-employee",
  STATISTIC_SUMMARY_BY_EMPLOYEE_DISCOUNT:
    "/statistic-summary/by-employee-discount",
  STATISTIC_SUMMARY_BY_PAYMENT_METHOD: "/statistic-summary/by-payment-method",
  STATISTIC_SUMMARY_BY_TIP: "/statistic-summary/by-tip",
  // statistic by date
  STATISTIC_DATE: "/statistic-date",
  STATISTIC_DATE_BY_SERVICE: "/statistic-date/by-service",
  STATISTIC_DATE_BY_EMPLOYEE: "/statistic-date/by-employee",
  STATISTIC_DATE_BY_EMPLOYEE_DISCOUNT: "/statistic-date/by-employee-discount",
  STATISTIC_DATE_BY_PAYMENT_METHOD: "/statistic-date/by-payment-method",
  STATISTIC_DATE_BY_TIP: "/statistic-date/by-tip",
  // ================= Not Found =================
  PAGE_NOT_FOUND: "/not-found",
};
